### ISSUE TITLE
Invalid grant: refresh token is invalid

### ISSUE THREAD

**Issue by karthick212** [pedroetb/node-oauth2-server-mongo-example#10]
Hello all, When I received a new token from the Refresh_token grant type I encountered "Invalid grant: refresh token is invalid". I stored tokens with AWS DynamoDB. In line of 135 in _node-oauth2-server-mongo-example/model.js_ file is referred to as token.client.id is client.clientId. It's not working for me. I tried to store the **client.id** instead of **client.clientId**. It's working fine now. Thanks for the oauth2-server example.

**Comment by pedroetb** [comment]
Thanks!
