### ISSUE TITLE
switch to client credentials grant type

### ISSUE THREAD

**Issue by vsantoro** [pedroetb/node-oauth2-server-mongo-example#2]
Password grant type is working great -  i can generate a toke.
I need to use the client_credentials grant type. What code change needs to be made to use it ?

**Comment by pedroetb** [comment]
In `app.js`, change this:
```
app.oauth = oauthserver({
	model: require('./model.js'),
	grants: ['password'],
	debug: true
});
```
with this:
```
app.oauth = oauthserver({
	model: require('./model.js'),
	grants: ['password', 'client_credentials'],
	debug: true
});
```
In other words, add **'client_credentials'** grant type to **grants** array.

**Comment by vsantoro** [comment]
Ok. I did that and tried get a token and I get

{
    "code": 400,
    "error": "invalid_client",
    "error_description": "The grant type is unauthorised for this client_id"
}

**Comment by vsantoro** [comment]
that is the error I get back in postman. This is the error that pops up in Node when i try and hit it with client credentials 

Connected successfully to "mongodb://localhost/oauth"
Error
    at OAuth2Error (/var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/error.js:30:12)
    at /var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/grant.js:343:19
    at Object.grantTypeAllowed (/var/www/html/node-oauth2-server-mongo-example/model.js:105:2)
    at Grant.checkGrantTypeAllowed (/var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/grant.js:338:14)
    at run (/var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/runner.js:15:14)
    at /var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/runner.js:17:7
    at /var/www/html/node-oauth2-server-mongo-example/node_modules/oauth2-server/lib/grant.js:147:5
    at Query.<anonymous> (/var/www/html/node-oauth2-server-mongo-example/node_modules/mongoose/lib/model.js:4081:16)
    at /var/www/html/node-oauth2-server-mongo-example/node_modules/kareem/index.js:273:21
    at /var/www/html/node-oauth2-server-mongo-example/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by pedroetb** [comment]
Can you share the full request you are sending? Maybe the *client_id* is wrong or just missing.

**Comment by vsantoro** [comment]
sure. here is the request with password grant type, its successful. 

![image](https://user-images.githubusercontent.com/6863614/41062521-10cbcaac-69a4-11e8-8e08-b7559cf5ca22.png)

**Comment by vsantoro** [comment]
![image](https://user-images.githubusercontent.com/6863614/41062556-288abcde-69a4-11e8-8a75-24fd2a5930b2.png)

**Comment by vsantoro** [comment]
![image](https://user-images.githubusercontent.com/6863614/41062575-3bae33ae-69a4-11e8-9833-01d4fd670865.png)

**Comment by vsantoro** [comment]
here is with client credentials
![image](https://user-images.githubusercontent.com/6863614/41062603-528523b2-69a4-11e8-94fd-fba345b2e677.png)

**Comment by vsantoro** [comment]
![image](https://user-images.githubusercontent.com/6863614/41062624-64be6534-69a4-11e8-9eea-d28a9cc3a528.png)

**Comment by vsantoro** [comment]
POST /oauth/token HTTP/1.1
Host: 10.80.141.163:3000
Authorization: Basic YXBwbGljYXRpb246c2VjcmV0
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 0c61eb42-55ec-5db8-225b-4a58e4a29d5b

grant_type=client_credentials&username=test&password=test

**Comment by vsantoro** [comment]
i tried with and without the username & pswd

**Comment by vsantoro** [comment]
any ideas how I can use the client_credentials grant type ? I also looked in model.js password grant type is defined for callback, i tried changing that to client_credentials but that also did not work.

**Comment by pedroetb** [comment]
You are missing the `Authorization` header with a valid combination of client identifier and secret Username and password are for users, you only need to identify the client (whole application, not a user of the application) with client_credentials grant type.

Check the readme of my [no-mongo repo](https://github.com/pedroetb/node-oauth2-server-example#with-client_credentials-grant-1) , it contains a basic example:
```
curl http://localhost:3000/oauth/token \
  -d "grant_type=client_credentials" \
  -H "Authorization: Basic Y29uZmlkZW50aWFsQXBwbGljYXRpb246dG9wU2VjcmV0" \
  -H "Content-Type: application/x-www-form-urlencoded"
```

**Comment by vsantoro** [comment]
Do I need to create a new client ? or is this client also in this repo code ?
There is one confidential client added to server and ready to work:
clientId: confidentialApplication
secret: topSecret

I am using Authorization in the header. Here is my current request.

POST /oauth/token HTTP/1.1
Host: 10.80.141.163:3000
Authorization: Basic YXBwbGljYXRpb246c2VjcmV0
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 7e612cbb-25eb-98f6-8619-68f7b1fbac8e

grant_type=client_credentials

Im using the default client
clientId: application
secret: secret

**Comment by vsantoro** [comment]
does my request look correct ?

**Comment by pedroetb** [comment]
My bad, this repo is outdated compared to the other one. There is no support for *client_credentials* grant type by now.

Soon I hope to spend some time updating these projects, to have the same possibilities. And maybe, upgrade to next major version (3.x) of oauth2-server.

Your last request seems ok, by the way!
