### ISSUE TITLE
HTTPS instead of HTTP

### ISSUE THREAD

**Issue by vsantoro** [pedroetb/node-oauth2-server-mongo-example#3]
what needs to be modified to use HTTPS instead of HTTP ? is this possible for Oauth2-Server

**Comment by pedroetb** [comment]
Serving in HTTPS can be achieved configuring the web server (Express.js on this example).
Also, is usual to delegate this task to a reverse proxy (Nginx, for example) between you and the app, so the protocol security is transparent to your backend app.
